### ISSUE TITLE
新版本不兼容吗?插件报错了

### ISSUE THREAD

**Issue by liaohui5** [fw6669998/Thinkphp5-Plugin#12]
![image](https://user-images.githubusercontent.com/29266093/57846038-ee518400-7805-11e9-9d64-058b7a5ced12.png)

![image](https://user-images.githubusercontent.com/29266093/57846072-05907180-7806-11e9-8b41-a54dfa9f7177.png)

**Comment by fw6669998** [comment]
可以把完整报错内容复制出来吗

**Comment by liaohui5** [comment]
没报错,是你没有修改收件人, 发送到我的邮箱了, 就算有报错也不可能发送到我的邮箱, 你可以找找laravel的日志,而且, 如果 qq 的个人邮箱, 不能一直发送邮件, 会被腾讯的服务器标识为垃圾邮件
而且, 发送频率太快就会被腾讯的服务器限制, 导致邮件发送失败
这些就是我在学习的时候遇到的问题和经验, 告诉你了, 记得修改收件人在测试, 别再发了




------------------ 原始邮件 ------------------
发件人: "fw6669998"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 晚上6:07
收件人: "fw6669998/Thinkphp5-Plugin"<Thinkphp5-Plugin@noreply.github.com>; 
抄送: "廖辉"<1182468610@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fw6669998/Thinkphp5-Plugin] 新版本不兼容吗?插件报错了 (#12)




可以把完整报错内容复制出来吗

**Comment by liaohui5** [comment]
刚刚那个邮件发错了, 抱歉, 我之前在简书上写了一个 经验总结, 忘记改收件人了, 填写我自己的,然后一直有人给我发邮件....


操作系统: windows 10 家庭中文版
状态: 有时候回提示重启, 有时候直接就弹窗提示
以下是报错信息:
-------------------------------------------------------------------------------------------------------------------------
com.intellij.diagnostic.PluginException: TypeProvider contract violation? by class pers.fw.tplugin.main.MyTypeProvider on model('index/') [Plugin: pers.fw.tplugin]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:368)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:68)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getType$1(PhpTypeInfo.java:85)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:116)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.getType(PhpTypeInfo.java:50)
	at com.jetbrains.php.lang.psi.elements.impl.PhpReferenceImpl.getType(PhpReferenceImpl.java:247)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.analyzeCall(PhpVoidFunctionResultUsedInspection.java:46)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection.access$000(PhpVoidFunctionResultUsedInspection.java:20)
	at com.jetbrains.php.lang.inspections.PhpVoidFunctionResultUsedInspection$1.visitPhpFunctionCall(PhpVoidFunctionResultUsedInspection.java:32)
	at com.jetbrains.php.lang.psi.elements.impl.FunctionReferenceImpl.accept(FunctionReferenceImpl.java:42)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:295)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:260)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecCC(ForkJoinPool.java:1190)
	at java.util.concurrent.ForkJoinPool.helpComplete(ForkJoinPool.java:1879)
	at java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:2045)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1036)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:71)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:198)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	at pers.fw.tplugin.main.MyTypeProvider.getType(MyTypeProvider.java:37)
	at com.jetbrains.php.lang.psi.resolve.types.PhpTypeInfo.lambda$getType$1(PhpTypeInfo.java:75)
	... 61 more

--------------------------------------------------------------------------------------------------------------------------------------------------





我是写PHP的,不会 java 呀, 难受 ~_~, 大神, 有时间修复下, 感谢!





------------------ 原始邮件 ------------------
发件人: "fw6669998"<notifications@github.com>; 
发送时间: 2019年7月12日(星期五) 晚上6:07
收件人: "fw6669998/Thinkphp5-Plugin"<Thinkphp5-Plugin@noreply.github.com>; 
抄送: "廖辉"<1182468610@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fw6669998/Thinkphp5-Plugin] 新版本不兼容吗?插件报错了 (#12)




可以把完整报错内容复制出来吗

**Comment by fw6669998** [comment]
试下新版1.3.6

**Comment by liaohui5** [comment]
更新之后, 用了近5个小时, 之前的bug没有再复现



------------------ 原始邮件 ------------------
发件人: "fw6669998"<notifications@github.com>; 
发送时间: 2019年7月16日(星期二) 下午4:59
收件人: "fw6669998/Thinkphp5-Plugin"<Thinkphp5-Plugin@noreply.github.com>; 
抄送: "廖辉"<1182468610@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [fw6669998/Thinkphp5-Plugin] 新版本不兼容吗?插件报错了 (#12)




试下新版1.3.6
