### ISSUE TITLE
在 PhpStorm2022.1 中打开TP5项目报错，详情如下

### ISSUE THREAD

**Issue by filesos** [fw6669998/Thinkphp5-Plugin#20]
Cannot process toolwindow TpLog

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at pers.fw.tplugin.log.ShowLog.value(ShowLog.java:13)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt:277)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt$computeToolWindowBeans$1.accept(ToolWindowSetInitializer.kt)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processWithPluginDescriptor(ExtensionPointImpl.java:301)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.computeToolWindowBeans(ToolWindowSetInitializer.kt:274)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:101)
	at com.intellij.toolWindow.ToolWindowSetInitializer$1.get(ToolWindowSetInitializer.kt:83)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by filesos** [comment]
希望作者可以修复一下

**Comment by filesos** [comment]
这个插件很不错，希望作者可以修复一下

**Comment by fw6669998** [comment]
修复了

**Comment by filesos** [comment]
感谢作者的持续更新，同时希望在最新版的 PhpStorm 2023.1 能支持一下，谢谢
